name: Check `ci-lab` compiles

on:
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  call-reusable-test:
    # TODO: Switch to `main` once merged
    uses: lurk-lab/ci-workflows/.github/workflows/check-downstream-compiles.yml@check-downstream-compiles
    with:
      repository: 'lurk-lab/ci-lab'
